package paint;
import java.awt.Color;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
public class PaintForm extends javax.swing.JFrame {

    /**
     * Creates new form PaintForm
     */
    public PaintForm() {
        initComponents();
((DrawingPanel)drawingPanel).setColor(Color.BLACK);

jTextField1.setBackground(Color.BLACK);

jTextField1.setOpaque(true);

jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(Color.GRAY));

jTextField1.setEditable(false);
jTextField1.setPreferredSize(new java.awt.Dimension(25, 25)); 
jTextField1.setMinimumSize(new java.awt.Dimension(25, 25)); 
jTextField1.setMaximumSize(new java.awt.Dimension(25, 25)); 


setSize(800, 600); 
setLocationRelativeTo(null); 

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        toolCombo = new javax.swing.JComboBox<>();
        thicknessCombo = new javax.swing.JComboBox<>();
        colorButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        clearButton = new javax.swing.JButton();
        importButton = new javax.swing.JButton();
        exportButton = new javax.swing.JButton();
        drawingPanel = new paint.DrawingPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        topPanel.setBackground(new java.awt.Color(117, 115, 115));

        toolCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ołówek", "Prostokąt", "Linia", "Okrąg", "Wielokąt" }));
        toolCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolComboActionPerformed(evt);
            }
        });
        topPanel.add(toolCombo);

        thicknessCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1px", "2px", "3px", "4px", "5px" }));
        thicknessCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thicknessComboActionPerformed(evt);
            }
        });
        topPanel.add(thicknessCombo);

        colorButton.setText("Kolor");
        colorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorButtonActionPerformed(evt);
            }
        });
        topPanel.add(colorButton);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        topPanel.add(jTextField1);

        clearButton.setText("Wyczyść");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        topPanel.add(clearButton);

        importButton.setText("Importuj");
        importButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importButtonActionPerformed(evt);
            }
        });
        topPanel.add(importButton);

        exportButton.setText("Eksportuj");
        exportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportButtonActionPerformed(evt);
            }
        });
        topPanel.add(exportButton);

        getContentPane().add(topPanel, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(drawingPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toolComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolComboActionPerformed
int idx = toolCombo.getSelectedIndex();
switch (idx) {
    case 0 -> ((DrawingPanel)drawingPanel).setTool(DrawingPanel.Tool.PENCIL);
    case 1 -> ((DrawingPanel)drawingPanel).setTool(DrawingPanel.Tool.RECT);
    case 2 -> ((DrawingPanel)drawingPanel).setTool(DrawingPanel.Tool.LINE);
    case 3 -> ((DrawingPanel)drawingPanel).setTool(DrawingPanel.Tool.OVAL);
    case 4 -> ((DrawingPanel)drawingPanel).setTool(DrawingPanel.Tool.POLYGON);
}

    }//GEN-LAST:event_toolComboActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
Color chosen = JColorChooser.showDialog(this, "Wybierz kolor", ((DrawingPanel)drawingPanel).getColor());
if (chosen != null) {
    ((DrawingPanel)drawingPanel).setColor(chosen);

    String hex = String.format("#%02X%02X%02X", chosen.getRed(), chosen.getGreen(), chosen.getBlue());
    jTextField1.setText(hex);
}

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void thicknessComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thicknessComboActionPerformed
String selected = (String) thicknessCombo.getSelectedItem();
if (selected != null && selected.endsWith("px")) {
    try {
        int t = Integer.parseInt(selected.replace("px", "").trim());
        ((DrawingPanel)drawingPanel).setThickness(t);
    } catch (NumberFormatException ex) {
        System.err.println("Błąd parsowania grubości: " + selected);
    }
}

    }//GEN-LAST:event_thicknessComboActionPerformed

    private void colorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorButtonActionPerformed
Color chosen = JColorChooser.showDialog(this, "Wybierz kolor", ((DrawingPanel)drawingPanel).getColor());
if (chosen != null) {
    ((DrawingPanel)drawingPanel).setColor(chosen);

    jTextField1.setBackground(chosen);
}

    }//GEN-LAST:event_colorButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
((DrawingPanel)drawingPanel).clearCanvas();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void importButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importButtonActionPerformed
                                       
    JFileChooser chooser = new JFileChooser();
    int result = chooser.showOpenDialog(this);
    if (result == JFileChooser.APPROVE_OPTION) {
        java.io.File file = chooser.getSelectedFile();
        ((DrawingPanel)drawingPanel).importImage(file);
    }
    }//GEN-LAST:event_importButtonActionPerformed

    private void exportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportButtonActionPerformed
            JFileChooser chooser = new JFileChooser();
    chooser.setDialogTitle("Zapisz projekt jako PNG");

    int result = chooser.showSaveDialog(this);
    if (result == JFileChooser.APPROVE_OPTION) {
        java.io.File file = chooser.getSelectedFile();

        if (!file.getName().toLowerCase().endsWith(".png")) {
            file = new java.io.File(file.getAbsolutePath() + ".png");
        }

        ((DrawingPanel)drawingPanel).saveImage(file);
        JOptionPane.showMessageDialog(this,
                "Projekt zapisany pomyślnie:\n" + file.getAbsolutePath(),
                "Sukces", JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_exportButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaintForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaintForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaintForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaintForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaintForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JButton colorButton;
    private javax.swing.JPanel drawingPanel;
    private javax.swing.JButton exportButton;
    private javax.swing.JButton importButton;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> thicknessCombo;
    private javax.swing.JComboBox<String> toolCombo;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
